package li.songe.morph.playground

import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material.icons.automirrored.filled.*
import androidx.compose.material.icons.outlined.*
import androidx.compose.ui.graphics.vector.ImageVector

internal data class IconEntry(
    val name: String,
    val imageVector: ImageVector,
)

internal val iconEntries =
    (listOf(
        IconEntry("Menu", Icons.Filled.Menu),
        IconEntry("Close", Icons.Filled.Close),
        IconEntry("Play", Icons.Filled.PlayArrow),
        IconEntry("Pause", Icons.Filled.Pause),
        IconEntry("Favorite border", Icons.Filled.FavoriteBorder),
        IconEntry("Favorite", Icons.Filled.Favorite),
        IconEntry("Add", Icons.Filled.Add),
        IconEntry("Remove", Icons.Filled.Remove),
        IconEntry("Home", Icons.Filled.Home),
        IconEntry("Search", Icons.Filled.Search),
        IconEntry("Settings", Icons.Filled.Settings),
        IconEntry("Person", Icons.Filled.Person),
        IconEntry("Star", Icons.Filled.Star),
        IconEntry("Star border", Icons.Filled.StarBorder),
        IconEntry("Check", Icons.Filled.Check),
        IconEntry("Arrow back", Icons.AutoMirrored.Filled.ArrowBack),
        IconEntry("Arrow forward", Icons.AutoMirrored.Filled.ArrowForward),
        IconEntry("Arrow up", Icons.Filled.ArrowUpward),
        IconEntry("Arrow down", Icons.Filled.ArrowDownward),
        IconEntry("Refresh", Icons.Filled.Refresh),
        IconEntry("Delete", Icons.Filled.Delete),
        IconEntry("Edit", Icons.Filled.Edit),
        IconEntry("Share", Icons.Filled.Share),
        IconEntry("Send", Icons.AutoMirrored.Filled.Send),
        IconEntry("Download", Icons.Filled.Download),
        IconEntry("Upload", Icons.Filled.Upload),
        IconEntry("Lock outline", Icons.Outlined.Lock),
        IconEntry("Lock open right", LockOpenRight),
        IconEntry("Visibility", Icons.Filled.Visibility),
        IconEntry("Visibility off", Icons.Filled.VisibilityOff),
        IconEntry("Notifications", Icons.Filled.Notifications),
        IconEntry("Notifications none", Icons.Filled.NotificationsNone),
        IconEntry("Email", Icons.Filled.Email),
        IconEntry("Phone", Icons.Filled.Phone),
        IconEntry("Location", Icons.Filled.LocationOn),
        IconEntry("Calendar", Icons.Filled.CalendarMonth),
        IconEntry("Time", Icons.Filled.AccessTime),
        IconEntry("Camera", Icons.Filled.CameraAlt),
        IconEntry("Photo", Icons.Filled.Photo),
        IconEntry("Mic", Icons.Filled.Mic),
        IconEntry("Volume", Icons.AutoMirrored.Filled.VolumeUp),
        IconEntry("Muted", Icons.AutoMirrored.Filled.VolumeOff),
        IconEntry("Wi-Fi", Icons.Filled.Wifi),
        IconEntry("Bluetooth", Icons.Filled.Bluetooth),
        IconEntry("Cloud", Icons.Filled.Cloud),
        IconEntry("Folder", Icons.Filled.Folder),
        IconEntry("Info", Icons.Filled.Info),
        IconEntry("Warning", Icons.Filled.Warning),
        IconEntry("Help", Icons.AutoMirrored.Filled.Help),
        IconEntry("Cart", Icons.Filled.ShoppingCart),
        IconEntry("ABC", Icons.Filled.Abc),
        IconEntry("AC unit", Icons.Filled.AcUnit),
        IconEntry("Access alarm", Icons.Filled.AccessAlarm),
        IconEntry("Accessibility", Icons.Filled.Accessibility),
        IconEntry("Account balance", Icons.Filled.AccountBalance),
        IconEntry("Account tree", Icons.Filled.AccountTree),
        IconEntry("ADB", Icons.Filled.Adb),
        IconEntry("Add alert", Icons.Filled.AddAlert),
        IconEntry("Add box", Icons.Filled.AddBox),
        IconEntry("Add business", Icons.Filled.AddBusiness),
        IconEntry("Add card", Icons.Filled.AddCard),
        IconEntry("Add chart", Icons.Filled.AddChart),
        IconEntry("Add comment", Icons.Filled.AddComment),
        IconEntry("Add home", Icons.Filled.AddHome),
        IconEntry("Add link", Icons.Filled.AddLink),
        IconEntry("Add location", Icons.Filled.AddLocation),
        IconEntry("Add photo", Icons.Filled.AddPhotoAlternate),
        IconEntry("Add reaction", Icons.Filled.AddReaction),
        IconEntry("Add cart", Icons.Filled.AddShoppingCart),
        IconEntry("Add task", Icons.Filled.AddTask),
        IconEntry("Adjust", Icons.Filled.Adjust),
        IconEntry("Agriculture", Icons.Filled.Agriculture),
        IconEntry("Air", Icons.Filled.Air),
        IconEntry("Airplane ticket", Icons.AutoMirrored.Filled.AirplaneTicket),
        IconEntry("Airplay", Icons.Filled.Airplay),
        IconEntry("Airport shuttle", Icons.Filled.AirportShuttle),
        IconEntry("Alarm", Icons.Filled.Alarm),
        IconEntry("Album", Icons.Filled.Album),
        IconEntry("Alternate email", Icons.Filled.AlternateEmail),
        IconEntry("Analytics", Icons.Filled.Analytics),
        IconEntry("Anchor", Icons.Filled.Anchor),
        IconEntry("Android", Icons.Filled.Android),
        IconEntry("Animation", Icons.Filled.Animation),
        IconEntry("Apartment", Icons.Filled.Apartment),
        IconEntry("API", Icons.Filled.Api),
        IconEntry("Apps", Icons.Filled.Apps),
        IconEntry("Architecture", Icons.Filled.Architecture),
        IconEntry("Archive", Icons.Filled.Archive),
        IconEntry("Arrow circle down", Icons.Filled.ArrowCircleDown),
        IconEntry("Arrow circle left", Icons.Filled.ArrowCircleLeft),
        IconEntry("Arrow circle right", Icons.Filled.ArrowCircleRight),
        IconEntry("Arrow circle up", Icons.Filled.ArrowCircleUp),
        IconEntry("Article", Icons.AutoMirrored.Filled.Article),
        IconEntry("Assessment", Icons.Filled.Assessment),
        IconEntry("Attach file", Icons.Filled.AttachFile),
        IconEntry("Attach money", Icons.Filled.AttachMoney),
        IconEntry("Audiotrack", Icons.Filled.Audiotrack),
        IconEntry("Auto awesome", Icons.Filled.AutoAwesome),
        IconEntry("Auto fix", Icons.Filled.AutoFixHigh),
        IconEntry("Backup", Icons.Filled.Backup),
        IconEntry("Access Alarms", Icons.Filled.AccessAlarms),
        IconEntry("Account Balance Wallet", Icons.Filled.AccountBalanceWallet),
        IconEntry("Add Alarm", Icons.Filled.AddAlarm),
        IconEntry("Add Location Alt", Icons.Filled.AddLocationAlt),
        IconEntry("Add To Photos", Icons.Filled.AddToPhotos),
        IconEntry("Ads Click", Icons.Filled.AdsClick),
        IconEntry("Airline Seat Legroom Normal", Icons.Filled.AirlineSeatLegroomNormal),
        IconEntry("Airlines", Icons.Filled.Airlines),
        IconEntry("Alarm On", Icons.Filled.AlarmOn),
        IconEntry("Align Vertical Center", Icons.Filled.AlignVerticalCenter),
        IconEntry("Alt Route", Icons.AutoMirrored.Filled.AltRoute),
        IconEntry("App Registration", Icons.Filled.AppRegistration),
        IconEntry("Arrow Back Ios", Icons.AutoMirrored.Filled.ArrowBackIos),
        IconEntry("Arrow Forward Ios", Icons.AutoMirrored.Filled.ArrowForwardIos),
        IconEntry("Art Track", Icons.Filled.ArtTrack),
        IconEntry("Assignment Return", Icons.AutoMirrored.Filled.AssignmentReturn),
        IconEntry("Assistant Direction", Icons.AutoMirrored.Filled.AssistantDirection),
        IconEntry("Attachment", Icons.Filled.Attachment),
        IconEntry("Auto Awesome Motion", Icons.Filled.AutoAwesomeMotion),
        IconEntry("Auto Mode", Icons.Filled.AutoMode),
        IconEntry("Baby Changing Station", Icons.Filled.BabyChangingStation),
        IconEntry("Badge", Icons.Filled.Badge),
        IconEntry("Bar Chart", Icons.Filled.BarChart),
        IconEntry("Battery2 Bar", Icons.Filled.Battery2Bar),
        IconEntry("Battery Alert", Icons.Filled.BatteryAlert),
        IconEntry("Battery Unknown", Icons.AutoMirrored.Filled.BatteryUnknown),
        IconEntry("Bedroom Parent", Icons.Filled.BedroomParent),
        IconEntry("Bike Scooter", Icons.Filled.BikeScooter),
        IconEntry("Blinds Closed", Icons.Filled.BlindsClosed),
        IconEntry("Bluetooth Disabled", Icons.Filled.BluetoothDisabled),
        IconEntry("Blur Off", Icons.Filled.BlurOff),
        IconEntry("Bookmark", Icons.Filled.Bookmark),
        IconEntry("Bookmarks", Icons.Filled.Bookmarks),
        IconEntry("Border Horizontal", Icons.Filled.BorderHorizontal),
        IconEntry("Border Style", Icons.Filled.BorderStyle),
        IconEntry("Brightness1", Icons.Filled.Brightness1),
        IconEntry("Brightness6", Icons.Filled.Brightness6),
        IconEntry("Brightness Medium", Icons.Filled.BrightnessMedium),
        IconEntry("Browser Not Supported", Icons.Filled.BrowserNotSupported),
        IconEntry("Bug Report", Icons.Filled.BugReport),
        IconEntry("Bus Alert", Icons.Filled.BusAlert),
        IconEntry("Cached", Icons.Filled.Cached),
        IconEntry("Calendar View Month", Icons.Filled.CalendarViewMonth),
        IconEntry("Call Merge", Icons.AutoMirrored.Filled.CallMerge),
        IconEntry("Call To Action", Icons.Filled.CallToAction),
        IconEntry("Camera Rear", Icons.Filled.CameraRear),
        IconEntry("Cancel Schedule Send", Icons.Filled.CancelScheduleSend),
        IconEntry("Card Giftcard", Icons.Filled.CardGiftcard),
        IconEntry("Casino", Icons.Filled.Casino),
        IconEntry("Catching Pokemon", Icons.Filled.CatchingPokemon),
        IconEntry("Center Focus Strong", Icons.Filled.CenterFocusStrong),
        IconEntry("Change Circle", Icons.Filled.ChangeCircle),
        IconEntry("Chat Bubble Outline", Icons.Filled.ChatBubbleOutline),
        IconEntry("Checklist", Icons.Filled.Checklist),
        IconEntry("Child Care", Icons.Filled.ChildCare),
        IconEntry("Circle Notifications", Icons.Filled.CircleNotifications),
        IconEntry("Clear All", Icons.Filled.ClearAll),
        IconEntry("Cloud Done", Icons.Filled.CloudDone),
        IconEntry("Cloud Upload", Icons.Filled.CloudUpload),
        IconEntry("Coffee", Icons.Filled.Coffee),
        IconEntry("Colorize", Icons.Filled.Colorize),
        IconEntry("Commute", Icons.Filled.Commute),
        IconEntry("Compress", Icons.Filled.Compress),
        IconEntry("Connecting Airports", Icons.Filled.ConnectingAirports),
        IconEntry("Contact Phone", Icons.Filled.ContactPhone),
        IconEntry("Content Cut", Icons.Filled.ContentCut),
        IconEntry("Contrast", Icons.Filled.Contrast),
        IconEntry("Copy All", Icons.Filled.CopyAll),
        IconEntry("Countertops", Icons.Filled.Countertops),
        IconEntry("Crib", Icons.Filled.Crib),
        IconEntry("Crop54", Icons.Filled.Crop54),
        IconEntry("Crop Original", Icons.Filled.CropOriginal),
        IconEntry("Css", Icons.Filled.Css),
        IconEntry("Currency Pound", Icons.Filled.CurrencyPound),
        IconEntry("Curtains", Icons.Filled.Curtains),
        IconEntry("Dashboard", Icons.Filled.Dashboard),
        IconEntry("Data Saver Off", Icons.Filled.DataSaverOff),
        IconEntry("Dataset Linked", Icons.Filled.DatasetLinked),
        IconEntry("Delete Forever", Icons.Filled.DeleteForever),
        IconEntry("Density Medium", Icons.Filled.DensityMedium),
        IconEntry("Desk", Icons.Filled.Desk),
        IconEntry("Developer Board", Icons.Filled.DeveloperBoard),
        IconEntry("Device Unknown", Icons.Filled.DeviceUnknown),
        IconEntry("Dialpad", Icons.Filled.Dialpad),
        IconEntry("Directions", Icons.Filled.Directions),
        IconEntry("Directions Bus Filled", Icons.Filled.DirectionsBusFilled),
        IconEntry("Directions Railway Filled", Icons.Filled.DirectionsRailwayFilled),
        IconEntry("Directions Transit Filled", Icons.Filled.DirectionsTransitFilled),
        IconEntry("Disc Full", Icons.Filled.DiscFull),
        IconEntry("Diversity3", Icons.Filled.Diversity3),
        IconEntry("Do Disturb On", Icons.Filled.DoDisturbOn),
        IconEntry("Do Not Disturb On Total Silence", Icons.Filled.DoNotDisturbOnTotalSilence),
        IconEntry("Domain Add", Icons.Filled.DomainAdd),
        IconEntry("Done Outline", Icons.Filled.DoneOutline),
        IconEntry("Door Sliding", Icons.Filled.DoorSliding),
        IconEntry("Download For Offline", Icons.Filled.DownloadForOffline),
        IconEntry("Draw", Icons.Filled.Draw),
        IconEntry("Drive Folder Upload", Icons.Filled.DriveFolderUpload),
        IconEntry("Dynamic Feed", Icons.Filled.DynamicFeed),
        IconEntry("East", Icons.Filled.East),
        IconEntry("Edit Calendar", Icons.Filled.EditCalendar),
        IconEntry("Edit Off", Icons.Filled.EditOff),
        IconEntry("Elderly", Icons.Filled.Elderly),
        IconEntry("Electric Moped", Icons.Filled.ElectricMoped),
        IconEntry("Emergency", Icons.Filled.Emergency),
        IconEntry("Emoji Flags", Icons.Filled.EmojiFlags),
        IconEntry("Emoji Symbols", Icons.Filled.EmojiSymbols),
        IconEntry("Equalizer", Icons.Filled.Equalizer),
        IconEntry("Euro", Icons.Filled.Euro),
        IconEntry("Event Busy", Icons.Filled.EventBusy),
        IconEntry("Expand", Icons.Filled.Expand),
        IconEntry("Explore", Icons.Filled.Explore),
        IconEntry("Exposure Plus1", Icons.Filled.ExposurePlus1),
        IconEntry("Face", Icons.Filled.Face),
        IconEntry("Face Retouching Natural", Icons.Filled.FaceRetouchingNatural),
        IconEntry("Family Restroom", Icons.Filled.FamilyRestroom),
        IconEntry("Featured Play List", Icons.AutoMirrored.Filled.FeaturedPlayList),
        IconEntry("Fence", Icons.Filled.Fence),
        IconEntry("Fiber Pin", Icons.Filled.FiberPin),
        IconEntry("File Download Off", Icons.Filled.FileDownloadOff),
        IconEntry("Filter1", Icons.Filled.Filter1),
        IconEntry("Filter6", Icons.Filled.Filter6),
        IconEntry("Filter Alt", Icons.Filled.FilterAlt),
        IconEntry("Filter Frames", Icons.Filled.FilterFrames),
        IconEntry("Filter Tilt Shift", Icons.Filled.FilterTiltShift),
        IconEntry("Fire Extinguisher", Icons.Filled.FireExtinguisher),
        IconEntry("Fitbit", Icons.Filled.Fitbit),
        IconEntry("Flare", Icons.Filled.Flare),
        IconEntry("Flashlight On", Icons.Filled.FlashlightOn),
        IconEntry("Flight Takeoff", Icons.Filled.FlightTakeoff),
        IconEntry("Flip To Front", Icons.Filled.FlipToFront),
        IconEntry("Fmd Bad", Icons.Filled.FmdBad),
        IconEntry("Folder Open", Icons.Filled.FolderOpen),
        IconEntry("Font Download", Icons.Filled.FontDownload),
        IconEntry("Fork Right", Icons.Filled.ForkRight),
        IconEntry("Format Bold", Icons.Filled.FormatBold),
        IconEntry("Format Indent Decrease", Icons.AutoMirrored.Filled.FormatIndentDecrease),
        IconEntry("Format List Numbered Rtl", Icons.Filled.FormatListNumberedRtl),
        IconEntry("Format Size", Icons.Filled.FormatSize),
        IconEntry("Fort", Icons.Filled.Fort),
        IconEntry("Forward5", Icons.Filled.Forward5),
        IconEntry("Front Hand", Icons.Filled.FrontHand),
        IconEntry("G Translate", Icons.Filled.GTranslate),
        IconEntry("Gavel", Icons.Filled.Gavel),
        IconEntry("Gif Box", Icons.Filled.GifBox),
        IconEntry("Gpp Good", Icons.Filled.GppGood),
        IconEntry("Grade", Icons.Filled.Grade),
        IconEntry("Grass", Icons.Filled.Grass),
        IconEntry("Grid On", Icons.Filled.GridOn),
        IconEntry("Group Work", Icons.Filled.GroupWork),
        IconEntry("H Plus Mobiledata", Icons.Filled.HPlusMobiledata),
        IconEntry("Hd", Icons.Filled.Hd),
        IconEntry("Hdr Off Select", Icons.Filled.HdrOffSelect),
        IconEntry("Hdr Weak", Icons.Filled.HdrWeak),
        IconEntry("Headset Off", Icons.Filled.HeadsetOff),
        IconEntry("Heart Broken", Icons.Filled.HeartBroken),
        IconEntry("Hevc", Icons.Filled.Hevc),
        IconEntry("Highlight", Icons.Filled.Highlight),
        IconEntry("History Edu", Icons.Filled.HistoryEdu),
        IconEntry("Holiday Village", Icons.Filled.HolidayVillage),
        IconEntry("Horizontal Rule", Icons.Filled.HorizontalRule),
        IconEntry("Hourglass Bottom", Icons.Filled.HourglassBottom),
        IconEntry("House", Icons.Filled.House),
        IconEntry("Html", Icons.Filled.Html),
        IconEntry("Ice Skating", Icons.Filled.IceSkating),
        IconEntry("Image Search", Icons.Filled.ImageSearch),
        IconEntry("Inbox", Icons.Filled.Inbox),
        IconEntry("Insert Chart Outlined", Icons.Filled.InsertChartOutlined),
        IconEntry("Insert Link", Icons.Filled.InsertLink),
        IconEntry("Install Mobile", Icons.Filled.InstallMobile),
        IconEntry("Inventory2", Icons.Filled.Inventory2),
        IconEntry("Javascript", Icons.Filled.Javascript),
        IconEntry("Kayaking", Icons.Filled.Kayaking),
        IconEntry("Keyboard Alt", Icons.Filled.KeyboardAlt),
        IconEntry("Keyboard Backspace", Icons.AutoMirrored.Filled.KeyboardBackspace),
        IconEntry("Keyboard Double Arrow Left", Icons.Filled.KeyboardDoubleArrowLeft),
        IconEntry("Keyboard Return", Icons.AutoMirrored.Filled.KeyboardReturn),
        IconEntry("Kitesurfing", Icons.Filled.Kitesurfing),
        IconEntry("Landscape", Icons.Filled.Landscape),
        IconEntry("Laptop Mac", Icons.Filled.LaptopMac),
        IconEntry("Layers Clear", Icons.Filled.LayersClear),
        IconEntry("Legend Toggle", Icons.Filled.LegendToggle),
        IconEntry("Library Books", Icons.AutoMirrored.Filled.LibraryBooks),
        IconEntry("Line Axis", Icons.Filled.LineAxis),
        IconEntry("Link Off", Icons.Filled.LinkOff),
        IconEntry("Live Help", Icons.AutoMirrored.Filled.LiveHelp),
        IconEntry("Local Atm", Icons.Filled.LocalAtm),
        IconEntry("Local Dining", Icons.Filled.LocalDining),
        IconEntry("Local Grocery Store", Icons.Filled.LocalGroceryStore),
        IconEntry("Local Mall", Icons.Filled.LocalMall),
        IconEntry("Local Phone", Icons.Filled.LocalPhone),
        IconEntry("Local Printshop", Icons.Filled.LocalPrintshop),
        IconEntry("Location Disabled", Icons.Filled.LocationDisabled),
        IconEntry("Lock Reset", Icons.Filled.LockReset),
        IconEntry("Looks4", Icons.Filled.Looks4),
        IconEntry("Loop", Icons.Filled.Loop),
        IconEntry("Lte Plus Mobiledata", Icons.Filled.LtePlusMobiledata),
        IconEntry("Mail", Icons.Filled.Mail),
        IconEntry("Man2", Icons.Filled.Man2),
        IconEntry("Manage Search", Icons.AutoMirrored.Filled.ManageSearch),
        IconEntry("Mark As Unread", Icons.Filled.MarkAsUnread),
        IconEntry("Mark Unread Chat Alt", Icons.Filled.MarkUnreadChatAlt),
        IconEntry("Media Bluetooth Off", Icons.Filled.MediaBluetoothOff),
        IconEntry("Medication", Icons.Filled.Medication),
        IconEntry("Merge", Icons.Filled.Merge),
        IconEntry("Mic None", Icons.Filled.MicNone),
        IconEntry("Miscellaneous Services", Icons.Filled.MiscellaneousServices),
        IconEntry("Mobile Screen Share", Icons.AutoMirrored.Filled.MobileScreenShare),
        IconEntry("Mode Edit Outline", Icons.Filled.ModeEditOutline),
        IconEntry("Model Training", Icons.Filled.ModelTraining),
        IconEntry("Monitor", Icons.Filled.Monitor),
        IconEntry("Mood Bad", Icons.Filled.MoodBad),
        IconEntry("More Vert", Icons.Filled.MoreVert),
        IconEntry("Motion Photos Pause", Icons.Filled.MotionPhotosPause),
        IconEntry("Move To Inbox", Icons.Filled.MoveToInbox),
        IconEntry("Moving", Icons.Filled.Moving),
        IconEntry("Music Note", Icons.Filled.MusicNote),
        IconEntry("Nature People", Icons.Filled.NaturePeople),
        IconEntry("Near Me Disabled", Icons.Filled.NearMeDisabled),
        IconEntry("Network Check", Icons.Filled.NetworkCheck),
        IconEntry("Network Wifi2 Bar", Icons.Filled.NetworkWifi2Bar),
        IconEntry("Next Plan", Icons.AutoMirrored.Filled.NextPlan),
        IconEntry("Nightlight", Icons.Filled.Nightlight),
        IconEntry("No Backpack", Icons.Filled.NoBackpack),
        IconEntry("No Encryption Gmailerrorred", Icons.Filled.NoEncryptionGmailerrorred),
        IconEntry("No Meeting Room", Icons.Filled.NoMeetingRoom),
        IconEntry("Noise Aware", Icons.Filled.NoiseAware),
        IconEntry("North West", Icons.Filled.NorthWest),
        IconEntry("Note Add", Icons.AutoMirrored.Filled.NoteAdd),
        IconEntry("Notifications Active", Icons.Filled.NotificationsActive),
        IconEntry("Offline Pin", Icons.Filled.OfflinePin),
        IconEntry("Online Prediction", Icons.Filled.OnlinePrediction),
        IconEntry("Open In New Off", Icons.Filled.OpenInNewOff),
        IconEntry("Outbox", Icons.Filled.Outbox),
        IconEntry("Padding", Icons.Filled.Padding),
        IconEntry("Pan Tool", Icons.Filled.PanTool),
        IconEntry("Panorama Horizontal Select", Icons.Filled.PanoramaHorizontalSelect),
        IconEntry("Panorama Wide Angle", Icons.Filled.PanoramaWideAngle),
        IconEntry("Password", Icons.Filled.Password),
        IconEntry("Pause Presentation", Icons.Filled.PausePresentation),
        IconEntry("Pentagon", Icons.Filled.Pentagon),
        IconEntry("Perm Camera Mic", Icons.Filled.PermCameraMic),
        IconEntry("Perm Media", Icons.Filled.PermMedia),
        IconEntry("Person4", Icons.Filled.Person4),
        IconEntry("Person Off", Icons.Filled.PersonOff),
        IconEntry("Person Remove Alt1", Icons.Filled.PersonRemoveAlt1),
        IconEntry("Pest Control Rodent", Icons.Filled.PestControlRodent),
        IconEntry("Phone Callback", Icons.AutoMirrored.Filled.PhoneCallback),
        IconEntry("Phone Iphone", Icons.Filled.PhoneIphone),
        IconEntry("Phonelink Erase", Icons.Filled.PhonelinkErase),
        IconEntry("Photo Album", Icons.Filled.PhotoAlbum),
        IconEntry("Photo Size Select Actual", Icons.Filled.PhotoSizeSelectActual),
        IconEntry("Piano Off", Icons.Filled.PianoOff),
        IconEntry("Pie Chart Outline", Icons.Filled.PieChartOutline),
        IconEntry("Pinch", Icons.Filled.Pinch),
        IconEntry("Play Circle", Icons.Filled.PlayCircle),
        IconEntry("Play Lesson", Icons.Filled.PlayLesson),
        IconEntry("Playlist Play", Icons.AutoMirrored.Filled.PlaylistPlay),
        IconEntry("Point Of Sale", Icons.Filled.PointOfSale),
        IconEntry("Pool", Icons.Filled.Pool),
        IconEntry("Power Input", Icons.Filled.PowerInput),
        IconEntry("Present To All", Icons.Filled.PresentToAll),
        IconEntry("Print Disabled", Icons.Filled.PrintDisabled),
        IconEntry("Propane Tank", Icons.Filled.PropaneTank),
        IconEntry("Publish", Icons.Filled.Publish),
        IconEntry("Qr Code2", Icons.Filled.QrCode2),
        IconEntry("Question Mark", Icons.Filled.QuestionMark),
        IconEntry("Quiz", Icons.Filled.Quiz),
        IconEntry("Radio Button Unchecked", Icons.Filled.RadioButtonUnchecked),
        IconEntry("Rate Review", Icons.Filled.RateReview),
        IconEntry("Receipt", Icons.Filled.Receipt),
        IconEntry("Rectangle", Icons.Filled.Rectangle),
        IconEntry("Remember Me", Icons.Filled.RememberMe),
        IconEntry("Remove Moderator", Icons.Filled.RemoveModerator),
        IconEntry("Repeat", Icons.Filled.Repeat),
        IconEntry("Replay10", Icons.Filled.Replay10),
        IconEntry("Reply All", Icons.AutoMirrored.Filled.ReplyAll),
        IconEntry("Request Page", Icons.Filled.RequestPage),
        IconEntry("Restaurant Menu", Icons.Filled.RestaurantMenu),
        IconEntry("Rice Bowl", Icons.Filled.RiceBowl),
        IconEntry("Roller Shades Closed", Icons.Filled.RollerShadesClosed),
        IconEntry("Room Service", Icons.Filled.RoomService),
        IconEntry("Roundabout Left", Icons.Filled.RoundaboutLeft),
        IconEntry("Rowing", Icons.Filled.Rowing),
        IconEntry("Rule Folder", Icons.Filled.RuleFolder),
        IconEntry("Sailing", Icons.Filled.Sailing),
        IconEntry("Save Alt", Icons.Filled.SaveAlt),
        IconEntry("Scanner", Icons.Filled.Scanner),
        IconEntry("School", Icons.Filled.School),
        IconEntry("Screen Lock Portrait", Icons.Filled.ScreenLockPortrait),
        IconEntry("Screen Share", Icons.AutoMirrored.Filled.ScreenShare),
        IconEntry("Sd Card", Icons.Filled.SdCard),
        IconEntry("Security Update", Icons.Filled.SecurityUpdate),
        IconEntry("Self Improvement", Icons.Filled.SelfImprovement),
        IconEntry("Sensor Door", Icons.Filled.SensorDoor),
        IconEntry("Sentiment Dissatisfied", Icons.Filled.SentimentDissatisfied),
        IconEntry("Sentiment Very Satisfied", Icons.Filled.SentimentVerySatisfied),
        IconEntry("Settings Brightness", Icons.Filled.SettingsBrightness),
        IconEntry("Settings Input Composite", Icons.Filled.SettingsInputComposite),
        IconEntry("Settings Power", Icons.Filled.SettingsPower),
        IconEntry("Severe Cold", Icons.Filled.SevereCold),
        IconEntry("Shop", Icons.Filled.Shop),
        IconEntry("Shopping Cart Checkout", Icons.Filled.ShoppingCartCheckout),
        IconEntry("Shuffle", Icons.Filled.Shuffle),
        IconEntry("Signal Cellular0 Bar", Icons.Filled.SignalCellular0Bar),
        IconEntry("Signal Cellular Connected No Internet0 Bar", Icons.Filled.SignalCellularConnectedNoInternet0Bar),
        IconEntry("Signal Cellular Off", Icons.Filled.SignalCellularOff),
        IconEntry("Signal Wifi Connected No Internet4", Icons.Filled.SignalWifiConnectedNoInternet4),
        IconEntry("Sim Card", Icons.Filled.SimCard),
        IconEntry("Skateboarding", Icons.Filled.Skateboarding),
        IconEntry("Slow Motion Video", Icons.Filled.SlowMotionVideo),
        IconEntry("Smartphone", Icons.Filled.Smartphone),
        IconEntry("Snippet Folder", Icons.Filled.SnippetFolder),
        IconEntry("Soap", Icons.Filled.Soap),
        IconEntry("Sos", Icons.Filled.Sos),
        IconEntry("South East", Icons.Filled.SouthEast),
        IconEntry("Spatial Audio", Icons.Filled.SpatialAudio),
        IconEntry("Speaker Notes", Icons.AutoMirrored.Filled.SpeakerNotes),
        IconEntry("Splitscreen", Icons.Filled.Splitscreen),
        IconEntry("Sports Basketball", Icons.Filled.SportsBasketball),
        IconEntry("Sports Handball", Icons.Filled.SportsHandball),
        IconEntry("Sports Motorsports", Icons.Filled.SportsMotorsports),
        IconEntry("Sports Volleyball", Icons.Filled.SportsVolleyball),
        IconEntry("Stacked Line Chart", Icons.Filled.StackedLineChart),
        IconEntry("Star Outline", Icons.Filled.StarOutline),
        IconEntry("Stay Current Landscape", Icons.Filled.StayCurrentLandscape),
        IconEntry("Stop", Icons.Filled.Stop),
        IconEntry("Store Mall Directory", Icons.Filled.StoreMallDirectory),
        IconEntry("Stream", Icons.Filled.Stream),
        IconEntry("Subdirectory Arrow Left", Icons.Filled.SubdirectoryArrowLeft),
        IconEntry("Subtitles", Icons.Filled.Subtitles),
        IconEntry("Supervisor Account", Icons.Filled.SupervisorAccount),
        IconEntry("Swap Calls", Icons.Filled.SwapCalls),
        IconEntry("Swipe", Icons.Filled.Swipe),
        IconEntry("Swipe Right", Icons.Filled.SwipeRight),
        IconEntry("Switch Access Shortcut", Icons.Filled.SwitchAccessShortcut),
        IconEntry("Switch Right", Icons.Filled.SwitchRight),
        IconEntry("Sync Disabled", Icons.Filled.SyncDisabled),
        IconEntry("System Security Update Warning", Icons.Filled.SystemSecurityUpdateWarning),
        IconEntry("Table Bar", Icons.Filled.TableBar),
        IconEntry("Tablet", Icons.Filled.Tablet),
        IconEntry("Takeout Dining", Icons.Filled.TakeoutDining),
        IconEntry("Temple Buddhist", Icons.Filled.TempleBuddhist),
        IconEntry("Text Fields", Icons.Filled.TextFields),
        IconEntry("Text Rotation Angledown", Icons.Filled.TextRotationAngledown),
        IconEntry("Textsms", Icons.Filled.Textsms),
        IconEntry("Thermostat Auto", Icons.Filled.ThermostatAuto),
        IconEntry("Thumb Up Alt", Icons.Filled.ThumbUpAlt),
        IconEntry("Timelapse", Icons.Filled.Timelapse),
        IconEntry("Timer3", Icons.Filled.Timer3),
        IconEntry("Title", Icons.Filled.Title),
        IconEntry("Token", Icons.Filled.Token),
        IconEntry("Touch App", Icons.Filled.TouchApp),
        IconEntry("Train", Icons.Filled.Train),
        IconEntry("Transit Enterexit", Icons.Filled.TransitEnterexit),
        IconEntry("Trending Up", Icons.AutoMirrored.Filled.TrendingUp),
        IconEntry("Tty", Icons.Filled.Tty),
        IconEntry("Turn Sharp Left", Icons.Filled.TurnSharpLeft),
        IconEntry("Turned In Not", Icons.Filled.TurnedInNot),
        IconEntry("U Turn Left", Icons.Filled.UTurnLeft),
        IconEntry("Unfold Less", Icons.Filled.UnfoldLess),
        IconEntry("Unsubscribe", Icons.Filled.Unsubscribe),
        IconEntry("Upload File", Icons.Filled.UploadFile),
        IconEntry("Vaping Rooms", Icons.Filled.VapingRooms),
        IconEntry("Vertical Align Top", Icons.Filled.VerticalAlignTop),
        IconEntry("Video Call", Icons.Filled.VideoCall),
        IconEntry("Video Label", Icons.Filled.VideoLabel),
        IconEntry("Videocam Off", Icons.Filled.VideocamOff),
        IconEntry("View Carousel", Icons.Filled.ViewCarousel),
        IconEntry("View Compact Alt", Icons.Filled.ViewCompactAlt),
        IconEntry("View Kanban", Icons.Filled.ViewKanban),
        IconEntry("View Stream", Icons.Filled.ViewStream),
        IconEntry("Voice Chat", Icons.Filled.VoiceChat),
        IconEntry("Volume Mute", Icons.AutoMirrored.Filled.VolumeMute),
        IconEntry("Vrpano", Icons.Filled.Vrpano),
        IconEntry("Wash", Icons.Filled.Wash),
        IconEntry("Water Damage", Icons.Filled.WaterDamage),
        IconEntry("Wb Cloudy", Icons.Filled.WbCloudy),
        IconEntry("Wb Twilight", Icons.Filled.WbTwilight),
        IconEntry("Web Stories", Icons.Filled.WebStories),
        IconEntry("Whatshot", Icons.Filled.Whatshot),
        IconEntry("Width Normal", Icons.Filled.WidthNormal),
        IconEntry("Wifi Calling3", Icons.Filled.WifiCalling3),
        IconEntry("Wifi Password", Icons.Filled.WifiPassword),
        IconEntry("Wifi Tethering Off", Icons.Filled.WifiTetheringOff),
        IconEntry("Woman2", Icons.Filled.Woman2),
        IconEntry("Workspace Premium", Icons.Filled.WorkspacePremium),
        IconEntry("Yard", Icons.Filled.Yard),
        IconEntry("10k", Icons.Filled._10k),
        IconEntry("13mp", Icons.Filled._13mp),
        IconEntry("18 Up Rating", Icons.Filled._18UpRating),
        IconEntry("1x Mobiledata", Icons.Filled._1xMobiledata),
        IconEntry("24mp", Icons.Filled._24mp),
        IconEntry("30fps Select", Icons.Filled._30fpsSelect),
        IconEntry("3k Plus", Icons.Filled._3kPlus),
        IconEntry("4k", Icons.Filled._4k),
        IconEntry("5k Plus", Icons.Filled._5kPlus),
        IconEntry("6k", Icons.Filled._6k),
        IconEntry("7mp", Icons.Filled._7mp),
        IconEntry("9mp", Icons.Filled._9mp),
        IconEntry("Lock", Icons.Filled.Lock),
        IconEntry("Lock open", Icons.Filled.LockOpen),
        IconEntry("Unlock outline", Icons.Outlined.LockOpen),
        IconEntry("Lock (Material Outlined)", Icons.Outlined.Lock),
    ) + additionalIconEntries()).also { entries ->
        check(entries.size == 2000) { "Expected 2000 icons" }
        check(entries.map { it.name }.distinct().size == entries.size) { "Icon names must be unique" }
    }

internal val iconCount: Int
    get() = iconEntries.size
